// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKotXhapp2a7ZWPrdqWPBQCaUKhvdYM0Y',
    appId: '1:636615947884:web:04149df01fd7707eec4a49',
    messagingSenderId: '636615947884',
    projectId: 'jojoe-65e9b',
    authDomain: 'jojoe-65e9b.firebaseapp.com',
    storageBucket: 'jojoe-65e9b.appspot.com',
    measurementId: 'G-QH78L9L1TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5aLaWxLqRLoEkO4wS6WvKLBpEW7I5AYs',
    appId: '1:636615947884:android:62ee0ab714d933fdec4a49',
    messagingSenderId: '636615947884',
    projectId: 'jojoe-65e9b',
    storageBucket: 'jojoe-65e9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2ZxQ4u88IYJ74oYgmpsrl2z3P4P5d2Y',
    appId: '1:636615947884:ios:7e849f5dfb7a7c80ec4a49',
    messagingSenderId: '636615947884',
    projectId: 'jojoe-65e9b',
    storageBucket: 'jojoe-65e9b.appspot.com',
    iosBundleId: 'com.example.jojoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2ZxQ4u88IYJ74oYgmpsrl2z3P4P5d2Y',
    appId: '1:636615947884:ios:d4e5bb3b5d76e6d9ec4a49',
    messagingSenderId: '636615947884',
    projectId: 'jojoe-65e9b',
    storageBucket: 'jojoe-65e9b.appspot.com',
    iosBundleId: 'com.example.jojoe.RunnerTests',
  );
}
